### ISSUE TITLE
Seção de Produto com responsividade quebrada

### ISSUE THREAD

**Issue by Thigos** [TechIdeas-ORG/site_institucional#3]
Section do produto está com a responsividade extramente quebrada. Talvez seja necessário recriar o layout de apresentação do produto
```index.html``` [Linha  145](https://github.com/TechIdeas-ORG/site_institucional/blob/c7fcb8c267013024f4609f6672596510c4cecc89/index.html#L145)

**Comment by GabrielBifon05** [comment]
problema resolvido dia 29/04. Será recriada nova tela, pois a equipe visa melhor design.

**Comment by GabrielBifon05** [comment]
problema resolvido dia 29/04. Será recriada nova tela, a equipe visa melhor design.
